name: Spell check

on:
    pull_request:
  
permissions:
    contents: read

jobs:
    spellcheck:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
            with:
                persist-credentials: false
    
          - name: Spellcheck all content
            uses: streetsidesoftware/cspell-action@eb29b6a67d122d2e6af385ff16bdb200d93b2e54 # v7.0.0
            with:
              config: .cspell.yaml       